# Author: Dhatri Badri

configfile: "config/config.yaml"

import pandas as pd
import os
import shutil, glob

# Load configuration
samples_df = pd.read_csv(config["samples"])
PREFIX = config["prefix"]
ASSEMBLY_DIR = config["assembly"]
SHORT_READS_DIR = config["short_reads"]

SAMPLE = list(samples_df["Sample_name"])

sample_ref_genome_dict = dict(zip(samples_df["Sample_name"], samples_df["Reference_genome_path"]))
sample_ref_genome_dict_gbk = dict(zip(samples_df["Sample_name"], samples_df["ref_genome_path_gbk"]))

if not os.path.exists("results/" + PREFIX):
    os.makedirs("results/" + PREFIX, exist_ok=True)

rule all:
    input:
        expand("results/{prefix}/final_results/{sample}.csv",prefix=PREFIX, sample=SAMPLE),
        # expand("results/{prefix}/snippy/{sample}/{sample}.csv", prefix=PREFIX, sample=SAMPLE),
        # expand("results/{prefix}/cauris_dotplot_repo/{sample}/plots/{sample}.pdf",prefix=PREFIX, sample=SAMPLE),
        # expand("results/{prefix}/cauris_dotplot_repo/dotplot.py", prefix=PREFIX)

####### rules #################
include: "rules/dotplot.smk"
include: "rules/snippy.smk"
include: "rules/organize_results.smk"
